#!/usr/bin/env node
/* Compiles src/app.jsx (JSX, class fields) to assets/app.js.
 *
 * Only JSX needs transforming - class fields, arrow functions, template
 * literals etc. are native in every browser this app supports, so the only
 * Babel plugin in play is the React preset. This replaces shipping
 * babel-standalone (~630KB gzipped) to the browser and compiling on every
 * load; see index.html, which loads the compiled output as a plain script.
 *
 * Output (assets/app.js) is git-ignored and regenerated before every
 * deploy - see the firebase.json predeploy hook and .github/workflows/*.yml.
 *
 *     node scripts/build-app.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { transform } from '@babel/core';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'src', 'app.jsx');
const OUT = join(ROOT, 'assets', 'app.js');

const source = readFileSync(SRC, 'utf8');
const result = transform(source, {
  filename: SRC,
  presets: [['@babel/preset-react', { runtime: 'classic', development: false }]],
  compact: false,
  comments: true,
  sourceType: 'script'
});

if (!result || !result.code) throw new Error('Babel produced no output for src/app.jsx');

const banner = '// Generated by scripts/build-app.mjs from src/app.jsx - do not edit directly.\n';
writeFileSync(OUT, banner + result.code + '\n');
console.log(`Compiled src/app.jsx -> assets/app.js (${(result.code.length / 1024).toFixed(0)}KB)`);
